In [1]:
import pandas as pd

In [5]:
scenario_test_outputs = pd.read_csv('./scenario_test_outputs.csv')
scenario_test_outputs.describe()

,prompt_idx,day,ema,minutes_late,ema_diff_squared,observed_mssd,user_threshold
count,18.000000,18.0,16.000000,18.000000,11.000000,11.000000,4.000000
mean,2.500000,0.0,3.062500,14.166667,8.090909,8.090909,8.000000
std,1.757338,0.0,1.481834,35.073452,8.005680,8.005680,9.237604
min,0.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.0,2.500000,0.000000,0.000000,0.000000,0.000000
50%,2.500000,0.0,3.000000,0.000000,9.000000,9.000000,8.000000
75%,4.000000,0.0,4.250000,0.000000,16.000000,16.000000,16.000000
max,5.000000,0.0,5.000000,120.000000,16.000000,16.000000,16.000000

In [6]:
decision_log = pd.read_csv('./outputs/decision_log.csv')
decision_log.head()

,user_id,timestamp,prompt_idx,day,ema,true_sigma,true_rho,true_expected_mssd,hr,ema_diff_squared,observed_mssd,user_threshold,send_prompt,decision_reason
0,0182313c-b6cd-4b34-a76d-d8c73d416c4f,2026-06-01 09:00:00,0,0,1.0,1.011861,0.374365,1.281128,79.412739,NaN,NaN,NaN,False,missing or insufficient EMA data
1,0182313c-b6cd-4b34-a76d-d8c73d416c4f,2026-06-01 12:00:00,1,0,2.0,1.011861,0.374365,1.281128,86.098377,1.0,1.0,NaN,False,insufficient within-person history
2,0182313c-b6cd-4b34-a76d-d8c73d416c4f,2026-06-01 15:00:00,2,0,3.0,1.011861,0.374365,1.281128,85.670289,1.0,1.0,NaN,False,insufficient within-person history
3,0182313c-b6cd-4b34-a76d-d8c73d416c4f,2026-06-01 18:00:00,3,0,2.0,1.011861,0.374365,1.281128,84.127873,1.0,1.0,NaN,False,insufficient within-person history
4,0182313c-b6cd-4b34-a76d-d8c73d416c4f,2026-06-01 21:00:00,4,0,1.0,1.011861,0.374365,1.281128,85.545036,1.0,1.0,1.0,False,below within-person threshold

In [7]:
decision_summary = pd.read_csv('./outputs/decision_summary.csv')
decision_summary.head()

,user_id,prompts_sent,average_mssd,max_mssd,average_threshold,max_threshold
0,0182313c-b6cd-4b34-a76d-d8c73d416c4f,43,1.251938,4.333333,1.424951,3.000000
1,05c4e378-f9e4-45da-ad97-d76fd3418173,26,1.187664,9.000000,1.136471,1.666667
2,20fa2a41-9da1-4386-8e86-f8acdec9dbc0,12,0.951567,4.000000,1.405988,2.400000
3,3a87968d-b84e-4445-828f-3e19f0e8f080,32,0.524306,2.666667,0.705098,1.000000
4,495c9078-4e5e-4c3c-be99-f4cf0418a334,22,1.290890,9.000000,1.879142,2.000000